### ISSUE TITLE
[SR] Support for working inside Vacuum Bags and Vacuum Ore Bags

### ISSUE THREAD

**Issue by vavavr00m** [direwolf420/ItemMagnetPlus#12]
The idea is to place the ItemMagnetPlus inside [Vacuum Bags](https://steamcommunity.com/sharedfiles/filedetails/?id=3023408924) and /or [Vacuum Ore Bags](https://steamcommunity.com/sharedfiles/filedetails/?id=3022671410) because ItemMagnetPlus has a configurable range and Vacuum Bags have configurable inventory slots.

**Comment by direwolf420** [comment]
That would only work if the mod the bags belong to calls UpdateInventory on the items inside it. If they don't call that, then the item magnet has no way of working. What stops you from just having it inside your main inventory, the items should go into the bags normally

**Comment by vavavr00m** [comment]
It's a bit finicky when there's a different player. I have reported to the Vacuum Bags' mod author. Thanks.
